-- Supprimer la table FAVORIS
DROP TABLE FAVORIS;

-- Supprimer la table BILLET
DROP TABLE BILLET;

-- Supprimer la table ACHETEUR
DROP TABLE ACHETEUR;

-- Supprimer la table CRENEAU
DROP TABLE CRENEAU;

-- Supprimer la table EVENTTYPE
DROP TABLE EVENTTYPE;

-- Supprimer la table ORGANISATIONARTISTE
DROP TABLE ORGANISATIONARTISTE;

-- Supprimer la table ARTISTE
DROP TABLE ARTISTE;

-- Supprimer la table STYLEMUSICAL
DROP TABLE STYLEMUSICAL;

-- Supprimer la table HEBERGEMENT
DROP TABLE HEBERGEMENT;

-- Supprimer la table LIEUSDUCONCERT
DROP TABLE LIEUSDUCONCERT;

-- Supprimer la table LIEU
DROP TABLE LIEU;

-- Supprimer la table CONCERT
DROP TABLE CONCERT;
